name: TemplateApp

options:
  deploymentTarget:
    iOS: 17.2
  defaultConfig: Release
  enableBaseInternationalization: false

configs:
  Debug: debug
  Release: release

settings:
  base:
    MARKETING_VERSION: 0.0.1
    SWIFT_VERSION: 5
    CLANG_CXX_LANGUAGE_STANDARD: gnu++20
    GCC_C_LANGUAGE_STANDARD: gnu17
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: YES
  configs:
    Debug:
      CONFIGURATION_NAME: debug
      BUNDLE_DISPLAY_NAME: TemplateApp|D
    Release:
      CONFIGURATION_NAME: release
      BUNDLE_DISPLAY_NAME: TemplateApp

targets:
  TemplateApp:
    type: application
    platform: iOS
    deploymentTarget: "17.2"
    sources:
      - TemplateApp
    scheme:
      testTargets:
        - TemplateAppTests
        - name: TemplateAppTests
          skipped: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.team.TemplateApp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_FILE: TemplateApp/Misc/Info.plist
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

    dependencies:
      - sdk: Foundation.framework
        
  TemplateAppTests:
    platform: iOS
    type: bundle.unit-test
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.team.TemplateApp.tests
    sources:
      - TemplateAppTests
    dependencies:
      - target: TemplateApp